  

 

preguntasMMPIAdolecente=[
'1. Me gustan las revistas de mecánica.',
'2. Tengo buen apetito.',
'3. Despierto descansado(a) y fresco(a) casi todas las mañanas.',
'4. Raras veces me preocupo por mi salud.',
'5. El ruido me despierta fácilmente.',
'6. Mi padre es un hombre bueno, o (si tu padre ha fallecido) fue un hombre bueno.',
'7. Me gusta leer los artículos sobre crímenes en los periódicos.',
'8. Por lo general tengo las manos y los pies lo suficientemente calientes.',
'9. Mi vida diaria está llena de cosas que mantienen mi interés.',
'10. Actualmente estoy tan capacitado(a) para trabajar como siempre lo he estado.',
'11. Siento un nudo en la garganta casi todo el tiempo.',
'12. Mis maestros quieren perjudicarme.',
'13. Me gustan las novelas de detectives o de misterio.',
'14. Trabajo bajo una gran presión.',
'15. De vez en cuando pienso en cosas demasiado malas como para hablar de ellas.',
'16. Estoy seguro(a) que la vida es injusta conmigo.',
'17. Sufro ataques de náusea y de vómito.',
'18. Muy raras veces padezco estreñimiento',
'19. A veces he sentido un intenso deseo de abandonar mi hogar.',
'20. Nadie parece comprenderme.',
'21. A veces me dan ataques de risa o de llanto que no puedo controlar.',
'22. En ocasiones los espíritus malignos se posesionan de mí.',
'23. Cuando estoy en problemas creo que lo mejor es quedarme callado(a).',
'24. Por principio, cuando alguien me hace algún mal siento que, de ser posible, debería pagarle con la misma moneda.',
'25. Padezco acidez estomacal varias veces a la semana.',
'26. En ocasiones siento deseos de maldecir.',
'27. Evito enfrentarme a los problemas o dificultades.',
'28. Tengo dificultades para concentrarme en una tarea o trabajo.',
'29. He tenido experiencias muy peculiares extrañas.',
'30. Algunas veces uso laxantes para no aumentar de peso.',
'31. Nunca he tenido dificultades a causa de mi conducta sexual.',
'32. Algunas veces he robado cosas.',
'33. Tengo miedo de ir a la escuela.',
'34. A veces siento ganas de destrozar las cosas.',
'35. He tenido periodos de días, semanas o meses,en los que no podía hacer nada. porque no tenía la energía suficiepte para empezar.',
'36. Mi sueño es irregular e intranquilo.',
'37. A menudo me parece que me duele toda la cabeza.',
'38. No siempre digo la verdad.',
'39. Si la gente no hubiera querido perjudicarme, tendría más éxito en la vida.',
'40. Soy más sensato ahora que nunca.',
'41. Una vez a la semana o más a menudo, de repente siento calor en todo el cuerpo, sin causa aparente.',
'42. Estoy tan sano(a) como la mayoría de mis amigos.',
'43. Prefiero hacerme el(la) desentendido(a) cuando veo a personas conocidas que no he visto por mucho tiempo, a no ser que ellas me hablen primero.',
'44. Casi nunca me ha dolido el corazón o el pecho.',
'45. Casi siempre preferiría soñar despierto(a) en lugar de hacer otra cosa.',
'46. Soy una persona muy sociable.',
'47. Con frecuencia he tenido que recibir órdenes de personas que sabían menos que yo.',
'48. No leo diariamente todos los artículos editoriales del periódico.',
'49. No he llevado una vida correcta.',
'50. Con frecuencia me parece sentir ardores, hormigueo o adormecimiento en algunas partes del cuerpo.',
'51. A mi familia no le gusta el trabajo al que pienso dedicarme.',
'52. Algunas veces me empeño tanto en algo que las personas pierden la paciencia conmigo.',
'53. Quisiera poder ser tan feliz como parecen serlo otras personas.',
'54. Muy raras veces siento dolor en la nuca.',
'55. Creo que mucha gente exagera sus desgracias para que los demás se compadezcan de ellos y los ayuden.',
'56. Sufro de malestares en la boca del estómago varios días a la semana o más frecuentemente.',
'57. A mis padres no les simpatizan mis amigos.',
'58. Soy una persona importante.',
'59. A menudo he deseado ser mujer, o (si tú eres mujer) nunca he lamentado ser mujer.',
'60. Las personas no lastiman mis sentimientos con facilidad.',
'61. Me gusta leer novelas de amor.',
'62. La mayor parte del tiempo me siento triste.',
'63. Sería mejor que se desecharan casi todas las leyes.',
'64. Me gusta la poesía.',
'65. A veces molesto a los animales.',
'66. Creo que me gustaría trabajar como guardabosques.',
'67. Pierdo fácilmente las discusiones.',
'68. En la actualidad me es dificil no perder la esperanza de llegar a ser alguien.',
'69. Pienso que la escuela es una pérdida de tiempo.',
'70. Definitivamente no tengo confianza en mí mismo(a).',
'71. Generalmente siento que la vida vale la pena.',
'72. Cuesta mucho trabajo convencer a la mayoría de la gente de la verdad.',
'73. De vez en cuando dejo para mañana lo que debiera hacer hoy.',
'74. Le agrado a la mayor parte de la gente que me conoce.',
'75. No me molesta que se burlen de mí.',
'76. Me gustaría ser enfermero(a).',
'77. Creo que la mayoría de la gente mentiría para salir adelante.',
'78. Hago muchas cosas de las que luego me arrepiento (me arrepiento más, o más frecuentemente que otras personas de lo que hago).',
'79. Tengo pocos disgustos con miembros de mi familia.',
'80. He sido suspendido(a) en la escuela una o más veces por mala conducta.',
'81. A veces siento un fuerte impulso de hacer algo dañino o escandaloso.',
'82. Me gusta ir a fiestas y reuniones animadas y alegres.',
'83. Me he enfrentado a problemas con tantas posibilidades de solución que no he podido llegar a una decisión.',
'84. Creo que la mujer debe tener tanta libertad sexual como el hombre.',
'85. Los conflictos más graves que tengo son conmigo mismo(a).',
'86. Quiero a mi padre, o (si tu padre ha fallecido) quise a mi padre.',
'87. Casi nunca tengo contracciones nerviosas o musculares.',
'88. No parece importarme lo que me pase.',
'89. Algunas veces, cuando no me siento bien, soy irritable.',
'90. Muchas veces tengo la sensación de haber hecho algo malo o diabólico.',
'91. Casi siempre soy feliz.',
'92. A mi alrededor veo cosas, animales o personas que otros no ven.',
'93. Siento opresión en la cabeza o la nariz congestionada la mayor parte del tiempo.',
'94. Algunas personas son tan mandonas que siento el deseo de hacer lo contrario de lo que me piden, aunque sepa que tienen la razón.',
'95. Alguien me quiere perjudicar.',
'96. Nunca he hecho algo peligroso sólo por el gusto de hacerlo.',
'97. A menudo siento como si tuviera una banda que me apretara la cabeza.',
'98. Algunas veces me enojo.',
'99. Disfruto más de una carrera o de un juego cuando apuesto.',
'100. La mayor parte de la gente es honrada principalmente por temor a ser descubierta.',
'101. En la escuela algunas veces me llevaron ante el director por mala conducta.',
'102. Mi manera de hablar es la misma de siempre (ni más rápida, ni más lenta, ni balbuceante, ni ronca).',
'103. Mis modales en la mésa no son tan buenos en casa como cuando salgo a comer con otras personas.',
'104. Cualquier persona que sea capaz y esté dispuesta a trabajar duro tiene buenas posibilidades de éxito.',
'105. Me parece que soy tan listo(a) y capaz corno la mayoría de los que me rodean.',
'106. Tengo muchos problemas estomacales.',
'107. La mayoría de las personas utilizarían medios indebidos para obtener lo que quieren.',
'108. A veces me provoco vómito después de comer para no aumentar de peso.',
'109. Sé quién es responsable de la mayoría de mis problemas.',
'110. Cuando veo sangre no me asusto ni me enfermo.',
'111. Con frecuencia no puedo comprender por qué he estado tan irritable y malhumorado(a).',
'112. No me preocupa contraer enfermedades.',
'113. Nunca he vomitado ni escupido sangre.',
'114. Me gusta recoger flores o cultivar plantas dentro de mi casa.',
'115. Con frecuencia siento la necesidad de luchar por lo que creo justo.',
'116. A veces mis pensamientos han pasado por mi mente con tanta rapidez que no he podido expresarlos en palabras.',
'117. Si pudiera entrar a un cine sin pagar y estuviera seguro(a) de no ser descubierto(a), probablemente lo haría.',
'118. A menudo me pregunto cuál será la verdadera intención de las personas que hacen algo bueno por mí.',
'119. Creo que mi vida hogareña es tan agradable como la de la mayoría de las personas que conozco.',
'120. Creo en el cumplimiento de la ley.',
'121. La crítica o el regaño me hieren profundamente.',
'122. Me gusta cocinar.',
'123. Mi conducta depende principalmente del comportamiento de las personas que me rodean.',
'124. Definitivamente, a veces me siento un inútil.',
'125. Pertenezco a un grupo de amigos que procuran ser leales ante todo tipo de problemas.',
'126. Creo que existe otra vida después de ésta.',
'127. Me gustaría ser soldado.',
'128. A veces siento el deseo de empezar una pelea a golpes con alguna persona.',
'129. Muchas veces he perdido oportunidades por no haberme decidido a tiempo.',
'130. Me impacienta que la gente me pida consejos o me interrumpa cuando estoy trabajando en algo importante.',
'131. Acostumbro llevar un diario sobre mi vida.',
'132. Creo que están tramando algo contra mí.',
'133. Prefiero ganar que perder en un juego.',
'134. Casi todas las noches me quedo dormido(a) sin tener pensamientos o ideas que me preocupen.',
'135. Durante los últimos años he gozado de buena salud la mayor parte del tiempo.',
'136. Creo que me están siguiendo.',
'137. Siento que frecuentemente he sido castigado(a) sin motivo.',
'138. Nunca he tenido un ataque o convulsiones.',
'139. Lloro fácilmente.',
'140. No subo ni bajo de peso.',
'141. No entiendo lo que leo tan bien como antes.',
'142. Nunca en mi vida me he sentido mejor que ahora.',
'143. A veces la parte superior de mi cabeza está muy sensible.',
'144. Tengo problemas con el alcohol o las drogas.',
'145. Me molesta que alguien me engañe tan hábilmente que tenga qué admitir que fui burlado(a).',
'146. No me canso con facilidad.',
'147. Me gusta conocer a gente importante porque eso me hace sentir importante.',
'148. Siento miedo cuando miro hacia abajo desde un lugar alto.',
'149. No me preocuparía si alguno de mis familiares tuviera problemas con la ley.',
'150. No me importa lo que otros piensen de mí.',
'151. Me siento incómodo(a) cuando tengo que hacer payasadas en una reunión, aun cuando los demás estén haciendo lo mismo.',
'152. Nunca me he desmayado.',
'153. Me gusta la escuela.',
'154. Frecuentemente tengo que esforzarme para no demostrar que soy tímido(a).',
'155. Alguien ha intentado envenenarme.',
'156. No tengo miedo a las serpientes.',
'157. Nunca o casi nunca tengo mareos.',
'158. Mi memoria parece estar en buenas condiciones.',
'159. Me preocupan las cuestiones sexuales.',
'160. Me cuesta trabajo entablar una conversación con alguien que acabo de conocer.',
'161. He tenido épocas durante las cuales he hecho cosas que luego no recuerdo haber hecho.',
'162. Cuando me aburro me gusta provocar algo emocionante o divertido.',
'163. Tengo miedo de perder el juicio.',
'164. Estoy en contra de dar dinero a los pordioseros.',
'165. Con frecuencia noto que mis manos tiemblan cuando trato de hacer algo.',
'166. Puedo leer durante mucho tiempo sin que se me cansen los ojos.',
'167. Siento debilidad general la mayor parte del tiempo.',
'168. Muy pocas veces me duele la cabeza.',
'169. Mis manos no se han entorpecido ni perdido habilidad.',
'170. Me gusta leer o estudiar acerca de las cosas en las que estoy trabajando.',
'171. Algunas veces cuando me apeno empiezo a sudar, cosa que me molesta muchísimo.',
'172. No he tenido dificultad en mantener el equilibrio cuando camino.',
'173. Algo anda mal en mi mente.',
'174. No me dan accesos de alergia o de asma.',
'175. He tenido ataques durante los cuales no podía controlar el habla o los movimientos, pero me daba cuenta de lo que ocurría a mi alrededor.',
'176. No me agradan todas las personas que conozco.',
'177. Algunas veces pienso en matarme.',
'178. Desearía no ser tan tímido(a).',
'179. Disfruto de distintas clases de juegos y diversiones.',
'180. Me gusta coquetear.',
'181. Mi familia me trata como a un(a) niño(a).',
'182. Mi madre es una mujer buena, o (si tu madre ha fallecido) mi madre era una mujer buena.',
'183. Cuando camino tengo mucho cuidado de no pisar las rayas en las banquetas.',
'184. En comparación con otros hogares, hay muy poco compañerismo y cariño en mi familia.',
'185. Frecuentemente me encuentro preocupado(a) por aleo.',
'186. Creo que me gustaría el trabajo de contratista de obras.',
'187. Tengo un problema físico que me impide disfrutar de otras actividades después de la escuela.',
'188. Me gusta la ciencia.',
'189. No se me dificulta pedir ayuda a mis amigos, aun cuando no pueda devolverles el favor.',
'190. Me gusta mucho cazar.',
'191. A menudo mis padres se oponen a la clase de gente que frecuento.',
'192. En ocasiones me gusta el chisme.',
'193. Aparentemente oigo tan bien como la mayoría de las personas.',
'194. Algunos de mis familiares tienen hábitos que me molestan o irritan mucho.',
'195. A veces creo que puedo.tomar decisiones con extraordinaria facilidad.',
'196. Raras veces noto los latidos de mi corazón, y muy pocas veces me falta la respiración.',
'197. Me gusta hablar sobre temas sexuales.',
'198. Me gusta visitar lugares donde nunca he estado.',
'199. Se me inculcó un modo de vida basado en el deber, el cual he seguido desde entonces con mucho cuidado.',
'200. Algunas veces he impedido que la gente consiguiera algo que quería, no porque eso fuera importante, sino por cuestión de principios.',
'201. Me enojo con facilidad, pero se me pasa pronto.',
'202. He sido bastante independiente y liberado(a) de la disciplina familiar.',
'203. Me preocupo mucho.',
'204. Casi todos mis parientes están de acuerdo conmigo.',
'205. Tengo periodos de tanta intranquilidad que no puedo permanecer sentado(a) mucho tiempo.',
'206. He tenido decepciones amorosas.',
'207. Nunca me preocupa mi apariencia fisica.',
'208. Sueño frecuentemente cosas que es mejor mantener en secreto.',
'209. No creo ser más nervioso(a) que la mayoría de las personas.',
'210. Padezco poca o ninguna clase de dolores.',
'211. Mi forma de hacer las cosas tiende a ser mal interpretada por otros.',
'212. Algunas veces sin razón, aun cuando las cosas van mal, me siento muy alegre, como si estuviera en la cima del mundo.',
'213. No culpo a nadie por tratar de apoderarse de todo lo que pueda en este mundo.',
'214. He tenido momentos en los que mi mente se ha quedado en blanco y no me daba cuenta de lo que ocurría a mi alrededor.',
'215. Mis padres realmente no me quieren.',
'216. Puedo ser amigable con personas que hacen cosas, que a mi manera de ver, son incorrectas.',
'217. Me gusta estar en un grupo en el que se hacen bromas los unos a los otros.',
'218. Se me dificulta comenzar a hacer las cosas.',
'219. Creo que estoy condenado(a).',
'220. Soy una persona lenta para aprender en la escuela.',
'221. No me importa no ser más guapo (bonita).',
'222. Sudo con facilidad, aun en días frescos.',
'223. Tengo entera confianza en mí mismo(a).',
'224. A veces me ha sido imposible evitar robar o llevarme algo de una tienda.',
'225. Es más seguro no confiar en nadie.',
'226. Una vez a la semana o más frecuentemente me pongo muy agitado(a).',
'227. Cuando estoy con un grupo de personas se me dificulta pensar en temas apropiados para platicar o conversar.',
'228. Cuando me siento triste, casi siempre algo emocionante me saca de ese estado.',
'229. Cuando salgo de casa no me preocupo por cerrar bien las ventanas)/ la puerta con llave.',
'230. Creo que mis pecados son imperdonables.',
'231. Se me adormecen una o varias partes de la piel.',
'232. No culpo a la persona que se aprovecha de otra, si esta última se expone a que le ocurra tal cosa.',
'233. Mi vista está tan bien ahora como lo ha estado por años.',
'234. A veces me divierte tanto la astucia de algún criminal, que he deseado que se salga con la suya.',
'235. Con frecuencia me ha parecido que algún extraño me miraba críticamente.',
'236. Todo me sabe igual.',
'237. Todos los días tomo una cantidad extraordinaria de agua.',
'238. La mayoría de las personas hacen amistades porque los amigos les pueden resultar útiles en algún momento.',
'239. Casi nunca noto que me zumben o silben los oídos.',
'240. De vez en cuando siento odio hacia los miembros de mi familia a los que usualmente quiero.',
'241. Si fuera reportero(a) me gustaría mucho escribir notas deportivas.',
'242. A nadie le importa mucho lo que le suceda a uno.',
'243. A veces me río de los chistes obscenos.',
'244. Tengo muy pocos temores en comparación con los de mis amigos.',
'245. No me sentiría apenado(a) si ante un grupo de personas tuviera que iniciar una discusión o dar una opinión acerca de algo que conozco bien.',
'246. Siempre me molesta que la justicia deje libre a un criminal debido a los recursos de un abogado astuto.',
'247. He bebido alcohol con exceso.',
'248. Por lo general no hablo a las personas, hasta que me hablen.',
'249. Nunca he tenido problemas con la ley.',
'250. A veces mi alma abandona mi cuerpo.',
'251. Quisiera que no me perturbaran pensamientos sexuales.',
'252. Si varias personas se hallan en apuros, lo mejor que pueden hacer es ponerse de acuerdo sobre lo que van a decir y mantenerse firmes en lo que acuerden.',
'253. Creo que siento más intensamente que la mayoría de las personas.',
'254. Nunca en mi vida me gustó jugar con muñecas.',
'255. A menudo la vida me resulta difícil.',
'256. Soy tan sensible respecto a algunos temas que ni siquiera puedo hablar de ellos.',
'257. En la escuela me es muy difícil hablar frente a la clase.',
'258. Quiero a mi madre, o (si tu madre ha fallecido) quise a mi madre.',
'259. Me siento solo(a) la mayor parte del tiempo, hasta cuando estoy con mucha gente.',
'260. Recibo toda la comprensión que debiera recibir.',
'261. Me niego a participar en algunos juegos porque no los sé jugar bien.',
'262. Creo que hago amistades tan fácilmente como cualquiera.',
'263. La persona que deja propiedades de valor sin protección es tan culpable del robo como el ladrón mismo.',
'264. No me gusta tener gente a mi alrededor.',
'265. Creo que casi todo el mundo mentiría para evitarse problemas.',
'266. Soy más sensible que la mayoría de la gente.',
'267. A la mayor parte de la gente le disgusta ayudar a los demás, aunque no lo diga.',
'268. Muchos de mis sueños están relacionados con el sexo.',
'269. Mi padres y familiares me encuentran más fallas de las que debieran.',
'270. Me avergüenzo muy fácilmente.',
'271. El dinero me preocupa.',
'272. Nunca he estado enamorado(a) de alguien.',
'273. Tengo miedo de usar cuchillos o cualquier otra cosa filosa o puntiaguda.',
'274. Casi nunca sueño.',
'275. Nunca he sufrido parálisis o alguna debilidad fuera de lo común en alguno de mis músculos.',
'276. Algunas veces pierdo o me cambia la voz, aunque no esté resfriado(a).',
'277. Mi madre o mi padre frecuentemente me hacen obedecerlos, aun cuando yo crea que no tienen la razón.',
'278. A veces percibo olores raros.',
'279. No me puedo concentrar en una sola cosa.',
'280. Tiendo a dejar de hacer algo que quiero, si otros creen que eso no vale la pena.',
'281. Casi todo el tiempo me siento preocupado(a) por algo o por alguien.',
'282. Pierdo fácilmente la paciencia con la gente.',
'283. La mayor parte del tiempo desearía estar muerto(a).',
'284. Algunas veces me siento tan inquieto(a) que me es difícil quedarme dormido(a).',
'285. Sin duda, he tenido más cosas de qué preocuparme de las que me corresponderían.',
'286. Estoy seguro(a) de que la gente habla de mí.',
'287. A veces me molesta oír tan bien.',
'288. Se me olvida muy pronto lo que me dicen.',
'289. A veces me siento lleno(a) de energía.',
'290. Con frecuencia cruzo la calle para evitar encontrarme con alguien que veo venir.',
'291. Muchas veces siento como si las cosas no fueran reales.',
'292. Me gustan las fiestas y las reuniones sociales.',
'293. Tengo la costumbre de contar cosas sin importancia, como la cantidad de focos en los anuncios luminosos y cosas por el estilo.',
'294. No tengo enemigos que realmente quieran hacerme daño.',
'295. Generalmente no me fío de las personas que son un poco más amigables de lo que esperaba.',
'296. Tengo pensamientos extraños y poco comunes.',
'297. Me pongo nervioso(a) y preocupado(a) cuando tengo que salir de casa para hacer un viaje corto.',
'298. Tengo periodos en que me siento muy alegre sin que exista una razón especial.',
'299. Oigo cosas extrañas cuando estoy solo(a).',
'300. He tenido miedo de cosas o personas que sabía que no podían hacerme daño.',
'301. No temo entrar solo(a) a un salón donde hay gente reunida platicando.',
'302. Algunos de mis familiares han hecho ciertas cosas que me han asustado.',
'303. Algunas veces disfruto al herir a las personas que quiero.',
'304. Siempre que me es posible, evito estar entre mucha gente.',
'305. Es más difícil para mí concentrarme, de lo que parece ser para otras personas.',
'306. En varias ocasiones he dejado de hacer algo porque he dudado de mi habilidad.',
'307. A menudo me vienen a la mente malas palabras, palabras horribles y me es imposible librarme de ellas.',
'308. Algunas veces me vienen a la mente pensamientos sin importancia que me molestan por días.',
'309. Casi todos los días sucede algo que me asusta.',
'310. Generalmente tengo que detenerme a pensar antes de hacer algo, aunque sea un asunto sin importancia.',
'311. Tengo la tendencia a tomar las cosas muy en serio.',
'312. A menudo platico con extraños en trenes, autobuses,etcétera.',
'313. La gente debería tratar de comprender sus sueños y guiarse por ellos o considerarlos como advertencias.',
'314. La gente dice cosas ofensivas y vulgares acerca de mí.',
'315. Alguien controla mi mente.',
'316. En las reuniones sociales o fiestas es más probable que me siente solo(a), o con una sola persona, en vez de reunirme con el grupo.',
'317. La gente me desilusiona con frecuencia.',
'318. Algunas veces he sentido que las dificultades se acumulan de tal modo que no puedo superarlas.',
'319. Me gusta muchísimo ir a bailes.',
'320. Durante ciertos periodos mi mente parece trabajar más lentamente que de costumbre.',
'321. A veces he sentido placer cuando un ser querido me ha lastimado.',
'322. Me gustan los niños.',
'323. Me gusta apostar cuando se trata de poco dinero.',
'324. Si me dieran la oportunidad, podría hacer algunas cosas que serían de gran beneficio para la humanidad.',
'325. Con frecuencia he conocido a personas supuestamente expertas y que no resultaron mejores que yo.',
'326. Me siento un(a) fracasado(a) cuando oigo hablar del éxito de alguien a quien conozco bien.',
'327. Pienso frecuentemente: "quisiera volver a ser niño(a)".',
'328. Nunca me siento más contento(a) que cuando estoy solo(a).',
'329. Si me dieran la oportunidad sería un(a) buen(a) líder(esa).',
'330. Las personas generalmente exigen más respeto para sus propios derechos, que el que están dispuestas a conceder a los demás.',
'331. Me gustan las reuniones sociales solo por estar con la gente.',
'332. Una o más veces en mi vida he sentido que alguien me obligaba a hacer cosas hipnotizándome.',
'333. Cuando inicio una tarea me es dificil hacerla a un lado, aunque sea por un momento.',
'334. A menudo me he encontrado personas que envidian mis buenas ideas, sólo porque a ellas no se les ocurrieron primero.',
'335. Disfruto con el alboroto de una multitud.',
'336. No me molesta conocer a personas extrañas.',
'337. Alguien ha tratado de influir en mi mente.',
'338. Recuerdo haberme fingido enfermo(a) para evitar algo.',
'339. Mis preocupaciones parecen desaparecer cuando estoy con un grupo de amigos animados.',
'340. Me rindo fácilmente cuando las cosas van mal.',
'341. Me gusta hacerle saber a la gente mi punto de vista sobre las cosas.',
'342. Solamente cuando bebo, puedo expresar lo que en verdad siento.',
'343. He tenido épocas en las que me sentía tan lleno de energía que me parecía que no necesitaba dormir durante varios días.',
'344. Estoy impaciente por que llegue el día en que pueda dejar mi casa para siempre.',
'345. Mis amigos se meten en problemas frecuentemente.',
'346. No le temo al agua.',
'347. No estoy contento(a)con mi manera de ser.',
'348. Me gustaría vestir ropa cara.',
'349. Tengo miedo de estar solo(a) en no sitio al descubierto.',
'350. Me siento incómodo(a) cuando estoy en lugares cerrados.',
'351. La única parte interesante del periódico es la de las caricaturas.',
'352. Tengo motivos para sentirme celoso(a) de uno o más miembros de mi familia.',
'353. Tengo pesadillas varias veces a la semana.',
'354. Puedo atemorizar fácilmente a la gente y a veces lo hago para divertirme.',
'355. No me enojo fácilmente.',
'356. En el pasado he hecho cosas malas que nunca he contado a nadie.',
'357. Me pongo nervioso(a) cuando me preguntan cosas personales.',
'358. No me siento capaz de planear mi futuro.',
'359. Me enojo cuando mi familia o amigos me aconsejan sobre cómo vivir mi vida.',
'360. Muy rara vez me siento deprimido(a).',
'361. Está bien burlarse de la ley, mientras no se llegue a violarla.',
'362. No me gusta escuchar a otras personas dar sus opiniones sobre la vida.',
'363. Con frecuencia tengo serios desacuerdos con personas importantes para mí.',
'364. A menudo me molestan las cosas que pasan en la escuela.',
'365. Cuando las cosas van muy mal, sé que puedo contar con la ayuda de mi familia.',
'366. He recibido muchas golpizas.',
'367. Me han dicho con frecuencia que tengo mal genio.',
'368. Quisiera dejar de preocuparme por las cosas que he dicho y que quizás hayan herido los sentimientos de otras personas.',
'369. Me siento incapaz de contarle a alguien todo acerca de mí.',
'370. Con frecuencia me ha parecido encontrar tantos obstáculos en mis planes que he tenido que abandonarlos.',
'371. El futuro es demasiado incierto para que una persona haga planes serios.',
'372. Con frecuencia, aun cuando todo vaya bien, siento que nada me importa.',
'373. Con frecuencia la gente ha interpretado mal mis intenciones cuando trataba de corregir algo y ayudar.',
'374. No tengo dificultades al tragar.',
'375. Por lo general soy tranquilo(a) y no me altero fácilmente.',
'376. Si me hallara en dificultades junto con varios amigos que fueran tan culpables como yo, preferiría echarme toda la culpa antes que descubrirlos.',
'377. Tiendo a tomar las desilusiones tan a pecho que no puedo dejar de pensar en ellas.',
'378. Cuando alguien trata de meterse en la fila, me molesta tanto, que le llamo la atención.',
'379. A veces pienso que no sirvo para nada.',
'380. Frecuentemente he faltado a la escuela aunque debía haber asistido.',
'381. Tengo uno o varios familiares que son muy nerviosos.',
'382. A veces he tenido que ser rudo(a) con personas groseras o inoportunas.',
'383. Me preocupo mucho por posibles desgracias.',
'384. Me siento incómodo(a) cuando la gente me halaga.',
'385. Tiendo a dejar de hacer algo que deseo, cuando los demás piensan que esa no es la manera correcta de hacerlo.',
'386. Me gusta lo emocionante.',
'387. Nunca he visto cosas extrañas.',
'388. Frecuentemente me siento apenado(a) por ser tan irritable y gruñón(a).',
'389. En la escuela mis calificaciones en conducta generalmente son malas.',
'390. Me fascina el fuego.',
'391. Cuando estoy en una situación dificil digo sólo aquella parte de la verdad que no me perjudica.',
'392. Merezco un severo castigo por mis pecados.',
'393. Me convierto rápidamente en partidario(a) de una buena idea.',
'394. Tengo que admitir que a veces me he preocupado demasiado por cosas que no valían la pena.',
'395. Frecuentemente he trabajado bajo las órdenes de personas que se atribuyen el reconocimiento por un buen trabajo, pero que culpan a los subordinados de los errores.',
'396. Algunos de mis familiares se enojan muy fácilmente.',
'397. Prefiero el trabajo que requiere mucha atención, al trabajo que me permite ser descuidado.',
'398. Los miembros de mi familia y mis parientes más cercanos se llevan bastante bien.',
'399. Me parece tener un porvenir sin esperanzas.',
'400. La gente puede hacerme cambiar de opinión muy fácilmente, aun cuando ya haya tomado una decisión.',
'401. Me molesta que la gente me apresure.',
'402. Varias veces por semana siento como si algo terrible fuera a suceder.',
'403. Me gusta leer sobre temas de ciencia.',
'404. A veces me siento al borde de una crisis nerviosa.',
'405. Odio a toda mi familia.',
'406. Un gran número de personas son culpables de mala conducta sexual.',
'407. La persona hacia la que he sentido mayor afecto y admiración es una mujer (madre, hermana, tía u otra mujer).',
'408. Algunas personas piensan que soy una persona dificil de llegar a conocer.',
'409. Me gusta leer los editoriales de los periódicos.',
'410. La mayoría de mi tiempo libre lo paso a solas.',
'411. Me gusta ir a conferencias sobre temas serios.',
'412. He tenido periodos en los cuales no he podido dormir por las preocupaciones.',
'413. Podría ser feliz viviendo solo(a) en una cabaña en el bosque o en las montañas.',
'414. Tengo uno o más malos hábitos tan arraigados que es inútil luchar contra ellos.',
'415. No puedo hacer nada bien.',
'416. Soy muy terco(a).',
'417. Los fantasmas o los espíritus pueden influir en las personas para bien o para mal.',
'418. No soy responsable de las cosas malas que me están pasando.',
'419. Los objetivos más importantes de mi vida están a mi alcance.',
'420. La enfermedad mental es señal de debilidad.',
'421. Me siento incapaz cuando tengo que tomar una decisión importante.',
'422. Todos mis problemas desaparecerían si estuviera mejor de salud.',
'423. Creo que las personas deberían guardar sus problemas personales para si mismas.',
'424. Actualmente no he sentido mucha tensión nerviosa.',
'425. Creo que mis maestros de la escuela son estúpidos.',
'426. Aunque no estoy satisfecho(a) con mi vida, nada puedo hacer ahora para cambiarla.',
'427. Odio admitir que me siento enfermo(a).',
'428. Hay personas que quieren apoderarse de mis pensamientos e ideas.',
'429. Tengo algunos hábitos que son realmente dañinos.',
'430. Cuando los problemas necesitan solución, generalmente dejo que otra persona se encargue del asunto.',
'431. Hablar con alguien sobre los problemas y preocupaciones es a menudo más provechoso que tomar drogas o medicinas.',
'432. Reconozco que tengo varios defectos que no seré capaz de cambiar.',
'433. Cuando estoy con gente, me molesta oír cosas muy extrañas.',
'434. Odio ir al doctor, aun cuando estoy enfermo(a).',
'435. Prefiero pasear en coche con mis amigos que participar en las actividades o eventos deportivos de la escuela.',
'436. Quiero estudiar en la universidad.',
'437. Encuentro alivio cuando comparto mis problemas con alguien.',
'438. Mis padres no me comprenden muy bien.',
'439. Frecuentemente oigo voces sin saber de dónde vienen.',
'440. He pasado noches fuera de mi casa en las que mis padres no sabían dónde estaba.',
'441. La gente piensa que no soy atractivo(a).',
'442. La gente siempre debería seguir sus creencias, aun cuando esto signifique romper las reglas.',
'443. He perdido muchos días de escuela debido a enfermedades.',
'444. Me molesta mucho pensar en hacer cambios en mi vida.',
'445. Frecuentemente tengo problemas por romper o destruir cosas.',
'446. La gente no es muy amable conmigo.',
'447. Por lo general espero tener éxito en lo que hago.',
'448. La mayoría de la gente piensa que puede confiar en mí.',
'449. Me es muy difícil romper con los malos hábitos.',
'450. Me llevo bien con la mayoría de la gente.',
'451. En mi familia no tenemos problemas para conversar entre nosotros.',
'452. Lo único bueno de la escuela son mis amigos.',
'453. Los demás dicen que hago berrinches para salirme con la mía.',
'454. Otras personas de mi familia parecen recibir más atención que yo.',
'455. Me han dicho frecuentemente que no respeto lo suficiente a las personas.',
'456. Me gusta escandalizar a la gente con las malas palabras que digo.',
'457. En mi casa hago lo que se espera que debo hacer.',
'458. Algunas veces me peleo cuando bebo.',
'459. Mis calificaciones en la escuela están dentro del promedio de mi grupo o arriba de éste.',
'460. Nunca me he escapado de mi casa.',
'461. A menudo tengo que gritar para hacer que comprendan mi punto de vista.',
'462. A menudo tengo que mentir para poder salir adelante.',
'463. No tengo amigos íntimos.',
'464. Los demás me dicen que soy un(a) flojo(a).',
'465. No me gusta tener que ser "rudo(a)" con la gente.',
'466. En la escuela a menudo me siento aburrido(a) y somnoliento(a).',
'467. Disfruto al fumar marihuana.',
'468. Con frecuencia me confundo y se me olvida lo que quiero decir.',
'469. A veces hago lo contrario de lo que otros quieren sólo para demostrarles que puedo.',
'470. Casi siempre tengo tos.',
'471. Evito a otras personas para que no se burlen de mí ni me molesten.',
'472. Tengo muchos secretos que me guardo para mí mismo(a).',
'473. Parece que no me divierto tanto como otros jóvenes de mi edad.',
'474. La gente me dice con frecuencia que bebo demasiado.',
'475. Generalmente soy muy tranquilo(a) con otras personas.',
'476. Tengo un(a) amigo(a) íntimo(a) con quien puedo compartir secretos.',
'477. Mis amigos me convencen frecuentemente de que haga cosas que sé que están mal.',
'478.  He hecho cosas malas que no quería, porque mis amigos pensaban que sí las debería hacer.'
];

preguntas=preguntasMMPIAdolecente;